1-run_nginx_as_nginx

diff --git a/0x12-web_stack_debugging_2/1-run_nginx_as_nginx b/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
--- a/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
+++ b/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
@@ -9,4 +9,19 @@ sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
 sudo sed -i 's/listen\s*80;listen 8080;/' /etc/nginx/sites-available/default
 sudo chmod 644 /etc/nginx/nginx.conf
 pkill apache2
-sudo -u nginx service nginx start
+sudo nginx -t || { echo "Nginx configuration test failed."; exit 1; }
+sudo service nginx restart
+if ps aux | grep '[n]ginx' | awk '{print $1}' | grep -q '^nginx$'; then
+	echo "Nginx is running as the nginx user."
+else
+	echo "Nginx is not running as the nginx user."
+	exit 1
+fi
+
+if netstat -tuln | grep ':8080'; then
+	echo "Nginx is listening on port 8080."
+else
+	echo "Nginx is not listening on port 8080."
+	exit 1
+fi
+
